import React,{useCallback,useEffect,useState} from 'react';
import {Alert,KeyboardAvoidingView,Platform,ScrollView,StatusBar,StyleSheet,Switch,Text,TouchableOpacity,View} from 'react-native';
import {api,Circle,Detail,Encounter,json,Person,Post} from './src/api';
import {Avatar,Button,Field,Pill,Section,styles} from './src/ui';
import {colors as c} from './src/theme';

type Page='Home'|'Explore'|'Create'|'Chats'|'Profile'|'Feed'|'Circle'|'Agent'|'Person'|'Encounter'|'Conversation'|'Events'|'Settings'|'Plus'|'Game';
type FeedTab='for_you'|'friends'|'circles';
const TABS:Page[]=['Home','Explore','Create','Chats','Profile'];

export default function App(){
  const [page,setPage]=useState<Page>('Home');
  const [me,setMe]=useState<Person|null>(null);
  const [circles,setCircles]=useState<Circle[]>([]);
  const [posts,setPosts]=useState<Post[]>([]);
  const [feedTab,setFeedTab]=useState<FeedTab>('for_you');
  const [circle,setCircle]=useState<Circle|null>(null);
  const [person,setPerson]=useState<Person|null>(null);
  const [encounter,setEncounter]=useState<Encounter|null>(null);
  const [detail,setDetail]=useState<Detail|null>(null);
  const [createKind,setCreateKind]=useState<'post'|'video'|'game'|'meetup'|null>(null);
  const [caption,setCaption]=useState('');
  const [visibility,setVisibility]=useState<'friends'|'public'>('friends');
  const [note,setNote]=useState('');
  const [query,setQuery]=useState('');
  const [draft,setDraft]=useState('');
  const [messages,setMessages]=useState<{id:number;sender_id:number;body:string;kind:string}[]>([]);
  const [friendsOpen,setFriendsOpen]=useState(true);
  const [groupsOpen,setGroupsOpen]=useState(true);
  const [events,setEvents]=useState<{id:number;title:string;kind:string;location:string|null;creator:Person}[]>([]);
  const [eventTitle,setEventTitle]=useState('');
  const [eventLocation,setEventLocation]=useState('');
  const notify=(e:unknown)=>Alert.alert('Aeolia',e instanceof Error?e.message:String(e));
  const refresh=useCallback(async()=>{
    try{const [m,cs]=await Promise.all([api<Person>('/me'),api<Circle[]>('/circles')]);setMe(m);setNote(m.preference_note||'');setCircles(cs)}catch(e){notify(e)}
  },[]);
  const refreshFeed=useCallback(async(tab:FeedTab=feedTab)=>{try{setPosts(await api<Post[]>(`/feed?tab=${tab}`))}catch(e){notify(e)}},[feedTab]);
  useEffect(()=>{refresh()},[]);
  useEffect(()=>{if(page==='Feed')refreshFeed();if(page==='Events')api<typeof events>('/events').then(setEvents).catch(notify)},[page,feedTab]);
  const openPerson=async(id:number)=>{try{setPerson(await api<Person>(`/users/${id}`));setPage('Person')}catch(e){notify(e)}};
  const openEncounter=async(e:Encounter)=>{if(!e.id)return;try{setEncounter(e);setDetail(await api<Detail>(`/encounters/${e.id}`));setPage('Encounter')}catch(err){notify(err)}};
  const openChat=async(p:Person)=>{try{setMessages(await api<typeof messages>(`/messages/${p.id}`));setPerson(p);setPage('Conversation')}catch(e){notify(e)}};
  const updateCircle=async(item:Circle,kind:'follow'|'explore')=>{try{await api(`/circles/${item.id}`,json('PATCH',{[kind]:!item[kind]}));setCircles(await api<Circle[]>('/circles'));setCircle(prev=>prev?.id===item.id?{...prev,[kind]:!item[kind]}:prev)}catch(e){notify(e)}};
  const explore=async(item:Circle)=>{try{const found=await api<Encounter>(`/explore/${item.id}`,{method:'POST'});if(found.id){setEncounter(found);await openEncounter(found)}else Alert.alert('Your agent',found.message||'No encounter yet')}catch(e){notify(e)}};
  const createPost=async()=>{try{await api('/posts',json('POST',{body:caption,visibility:circle&&visibility==='public'? 'public':visibility,circle_id:circle&&visibility==='public'?circle.id:null,media_type:'text'}));setCaption('');setCreateKind(null);setPage('Feed');refreshFeed()}catch(e){notify(e)}};
  const createEvent=async(kind:'game'|'meetup')=>{try{await api('/events',json('POST',{title:eventTitle|| (kind==='game'?'Draw & Guess':'Coffee & sketches'),kind,location:kind==='meetup'?eventLocation:null}));setEventTitle('');setCreateKind(null);setPage(kind==='game'?'Game':'Events')}catch(e){notify(e)}};
  const goTab=(tab:Page)=>{setCircle(null);setCreateKind(null);setPage(tab)};
  const header=(title:string,back:Page='Home')=><View style={ui.header}><TouchableOpacity onPress={()=>setPage(back)}><Text style={ui.back}>‹</Text></TouchableOpacity><Text style={ui.headerTitle}>{title}</Text><View style={{width:22}}/></View>;
  const userRow=(p:Person,onPress:()=>void,subtitle?:string)=><TouchableOpacity onPress={onPress} style={ui.row}><Avatar outfit={p.outfit}/><View style={{flex:1,marginLeft:12}}><Text style={ui.rowTitle}>{p.name}</Text><Text style={styles.muted}>{subtitle||`${p.job} · ${p.city}`}</Text></View><Text style={styles.muted}>›</Text></TouchableOpacity>;
  const postCard=(p:Post)=><View key={p.id} style={[styles.card,{marginBottom:12}]}><TouchableOpacity onPress={()=>openPerson(p.author.id)} style={{flexDirection:'row',alignItems:'center',gap:10}}><Avatar size={40} outfit={p.author.outfit}/><View><Text style={ui.rowTitle}>{p.author.name}</Text><Text style={styles.muted}>{p.circle_id?circles.find(x=>x.id===p.circle_id)?.name+' · Public circle':p.visibility==='public'?'Public':'Friends only'}</Text></View></TouchableOpacity><Text style={[styles.text,{marginTop:12,lineHeight:23}]}>{p.body}</Text><Text style={[styles.muted,{marginTop:12}]}>♡   Comment    ↗ Share</Text></View>;
  const pageContent=()=>{
    if(page==='Home')return <ScrollView contentContainerStyle={styles.body}><Text style={ui.brand}>◌ Aeolia</Text><Text style={[styles.title,{marginTop:18}]}>Good afternoon</Text><Text style={[styles.muted,{marginBottom:20}]}>Brighter connections start here.</Text><View style={[styles.card,{backgroundColor:'#F1F8F5',flexDirection:'row',alignItems:'center',marginBottom:17}]}><Avatar size={112} outfit={me?.outfit}/><View style={{flex:1,marginLeft:14}}><Text style={styles.heading}>Your agent</Text><Text style={[styles.muted,{marginVertical:9}]}>Getting to know your vibe and finding people you might like.</Text><Button label="Talk to agent" onPress={()=>setPage('Agent')}/><View style={{height:7}}/><Button label="Change outfit" onPress={()=>setPage('Profile')} secondary/></View></View><View style={{flexDirection:'row',gap:10,marginBottom:22}}><TouchableOpacity onPress={()=>setPage('Feed')} style={[styles.card,ui.homeShortcut,{backgroundColor:c.mint}]}><Text style={ui.shortcutIcon}>♧</Text><Text style={styles.heading}>Friends</Text><Text style={styles.muted}>Posts from friends and circles</Text></TouchableOpacity><TouchableOpacity onPress={()=>setPage('Events')} style={[styles.card,ui.homeShortcut,{backgroundColor:c.apricot}]}><Text style={ui.shortcutIcon}>▣</Text><Text style={styles.heading}>Events</Text><Text style={styles.muted}>Plans & game rooms</Text></TouchableOpacity></View><Section title="For you" action={<TouchableOpacity onPress={()=>setPage('Explore')}><Text style={styles.muted}>See more ›</Text></TouchableOpacity>}>{userRow({id:2,name:'Kai',handle:'kai.2048',outfit:'apricot',city:'San Francisco',job:'Product designer',bio:'',interests:[]},()=>openPerson(2),'Your agent may find a shared conversation.')}</Section><Section title="Circle updates">{circles.filter(x=>x.follow).map(x=><TouchableOpacity key={x.id} onPress={()=>{setCircle(x);setPage('Circle')}} style={[styles.card,{marginBottom:8}]}><Text style={ui.rowTitle}>{x.name}  ›</Text><Text style={styles.muted}>{x.description}</Text></TouchableOpacity>)}</Section></ScrollView>;
    if(page==='Feed')return <>{header('Feed')}<ScrollView contentContainerStyle={styles.body}><View style={ui.pills}>{([['for_you','For you'],['friends','Friends'],['circles','Following circles']] as const).map(([key,label])=><Pill key={key} label={label} active={feedTab===key} onPress={()=>setFeedTab(key)}/>)}</View><TouchableOpacity style={[styles.card,{marginBottom:18}]} onPress={()=>{setCreateKind('post');setPage('Create')}}><Text style={styles.muted}>What would you like to share?  +</Text></TouchableOpacity>{posts.map(postCard)}<Text style={styles.muted}>Sponsored posts will be clearly labelled when ads are enabled.</Text></ScrollView></>;
    if(page==='Explore')return <ScrollView contentContainerStyle={styles.body}><Text style={styles.title}>Explore</Text><Text style={[styles.muted,{marginBottom:20}]}>Your agent wanders through circles, with room for chance.</Text><Section title="Choose a circle">{circles.map(x=><TouchableOpacity key={x.id} style={[styles.card,{marginBottom:9}]} onPress={()=>{setCircle(x);setPage('Circle')}}><Text style={ui.rowTitle}>◎  {x.name}  ›</Text><Text style={styles.muted}>{x.description}</Text><View style={{flexDirection:'row',marginTop:10,gap:8}}><Button label="Open circle" secondary onPress={()=>{setCircle(x);setPage('Circle')}}/><Button label="Send agent" onPress={()=>explore(x)}/></View></TouchableOpacity>)}</Section><Section title="Chance encounters"><View style={ui.graph}><View style={ui.graphLine}/><View style={ui.graphLine2}/><View style={{position:'absolute',left:'39%',top:'33%'}}><Avatar size={76} outfit={me?.outfit}/><Text style={styles.muted}>You</Text></View>{['apricot','sage','navy'].map((outfit,i)=><View key={outfit} style={{position:'absolute',left:i===0?'10%':i===1?'70%':'67%',top:i===0?'13%':i===1?'9%':'68%'}}><Avatar outfit={outfit} size={55}/></View>)}</View></Section><Text style={styles.muted}>People shown here use their agent avatars. Tapping a recommendation opens the real profile.</Text></ScrollView>;
    if(page==='Circle'&&circle){const actual=circles.find(x=>x.id===circle.id)||circle;return <>{header(actual.name,'Explore')}<ScrollView contentContainerStyle={styles.body}><Text style={styles.muted}>{actual.description}</Text><Text style={[styles.muted,{marginVertical:12}]}>Posts here are public. Following adds them to your feed.</Text><Button label={actual.follow?'Following ✓':'Follow circle'} onPress={()=>updateCircle(actual,'follow')}/><TouchableOpacity onPress={()=>updateCircle(actual,'explore')} style={[styles.card,{marginTop:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'}]}><View style={{flex:1}}><Text style={ui.rowTitle}>Let my agent explore</Text><Text style={styles.muted}>Separate from following the feed</Text></View><Switch value={actual.explore} onValueChange={()=>updateCircle(actual,'explore')} trackColor={{true:c.teal}}/></TouchableOpacity><View style={{height:12}}/><Button label="Send agent exploring" onPress={()=>explore(actual)}/><Text style={[styles.heading,{marginTop:25,marginBottom:12}]}>Public posts</Text><CirclePosts id={actual.id} openPerson={openPerson}/></ScrollView></>}
    if(page==='Create')return <>{header('Create')}<ScrollView contentContainerStyle={styles.body}>{!createKind?<><Text style={[styles.muted,{marginBottom:16}]}>Choose what to share or play.</Text>{([['post','Post','Share photos or thoughts'],['video','Video','Share a short clip'],['game','Game room','Play online with friends'],['meetup','Meetup plan','Make an in-person plan']] as const).map(([key,label,sub])=><TouchableOpacity key={key} style={[styles.card,{marginBottom:10}]} onPress={()=>setCreateKind(key)}><Text style={ui.rowTitle}>{label}  ›</Text><Text style={styles.muted}>{sub}</Text></TouchableOpacity>)}</>:createKind==='post'||createKind==='video'?<><Text style={styles.heading}>New {createKind}</Text><Text style={[styles.muted,{marginBottom:12}]}>Photos and video upload will be connected in the next milestone. Text posts work now.</Text><View style={[styles.card,{height:150,alignItems:'center',justifyContent:'center',marginBottom:16}]}><Text style={styles.muted}>＋ Add {createKind==='video'?'video':'photos'}</Text></View><Field placeholder="Write a caption…" value={caption} onChangeText={setCaption} multiline style={{minHeight:100,textAlignVertical:'top'}}/><Text style={[ui.rowTitle,{marginBottom:8}]}>Audience</Text><View style={ui.pills}><Pill label="Friends" active={visibility==='friends'} onPress={()=>setVisibility('friends')}/><Pill label="Public" active={visibility==='public'} onPress={()=>setVisibility('public')}/></View><Text style={[styles.muted,{marginBottom:16}]}>Friends means mutual friends only. Circle posts must be public.</Text><Button label="Share" onPress={createPost}/></>:<><Text style={styles.heading}>{createKind==='game'?'Start an online game':'Plan an in-person meetup'}</Text><View style={{height:16}}/><Field value={eventTitle} onChangeText={setEventTitle} placeholder={createKind==='game'?'Draw & Guess':'Coffee & sketches'}/>{createKind==='meetup'&&<Field value={eventLocation} onChangeText={setEventLocation} placeholder="Broad location (optional)"/>}<Button label={createKind==='game'?'Create & enter room':'Create plan'} onPress={()=>createEvent(createKind)}/></>}</ScrollView></>;
    if(page==='Agent')return <>{header('My agent')}<ScrollView contentContainerStyle={styles.body}><View style={{alignItems:'center',padding:14}}><Avatar size={104} outfit={me?.outfit}/><Text style={[styles.heading,{marginTop:12}]}>Learning your vibe</Text><Text style={styles.muted}>Your private preferences stay with your agent.</Text></View><Section title="Tell me about the people you like"><Field multiline value={note} onChangeText={setNote} style={{height:140,textAlignVertical:'top'}} placeholder="I like curious people who enjoy cozy games…"/><Button label="Save my preferences" onPress={async()=>{try{await api('/me',json('PATCH',{preference_note:note}));Alert.alert('Saved','Your agent will remember this.')}catch(e){notify(e)}}}/></Section><Section title="What my agent remembers"><View style={styles.card}><Text style={styles.text}>{note||'Tell your agent what kind of friends you hope to meet.'}</Text></View></Section><Text style={styles.muted}>This demo stores your preferences. A full conversational AI and imitation of your tone are future integrations.</Text></ScrollView></>;
    if(page==='Profile')return <ScrollView contentContainerStyle={styles.body}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={styles.title}>My profile</Text><TouchableOpacity onPress={()=>setPage('Settings')}><Text style={{fontSize:25,color:c.teal}}>⚙</Text></TouchableOpacity></View><View style={[styles.card,{alignItems:'center',marginTop:16}]}><Avatar size={110} outfit={me?.outfit}/><Text style={[styles.heading,{marginTop:12}]}>@{me?.handle}</Text><Text style={styles.muted}>Aeolia ID · {me?.handle}</Text><Text style={[styles.text,{marginTop:12}]}>{me?.job} · {me?.city}</Text><Text style={[styles.muted,{marginTop:7,textAlign:'center'}]}>{me?.bio}</Text><View style={[ui.pills,{marginTop:15,justifyContent:'center'}]}>{me?.interests.map(x=><Pill key={x} label={x} onPress={()=>{}}/>)}</View></View><Section title="My avatar"><View style={[styles.card,{flexDirection:'row',alignItems:'center',gap:12}]}><Avatar outfit={me?.outfit}/><View style={{flex:1}}><Text style={ui.rowTitle}>Change outfit</Text><Text style={styles.muted}>Your look in the graph and chat</Text></View></View><View style={[ui.pills,{marginTop:10}]}>{['teal','apricot','sage','navy'].map(o=><Pill key={o} label={o} active={me?.outfit===o} onPress={async()=>{try{const m=await api<Person>('/me',json('PATCH',{outfit:o}));setMe(m)}catch(e){notify(e)}}}/>)}</View></Section><Button label="Settings & subscription" onPress={()=>setPage('Settings')}/></ScrollView>;
    if(page==='Person'&&person)return <>{header(person.name,'Explore')}<ScrollView contentContainerStyle={styles.body}><View style={[styles.card,{alignItems:'center'}]}><Avatar outfit={person.outfit} size={100}/><Text style={[styles.heading,{marginTop:10}]}>@{person.handle}</Text><Text style={styles.muted}>{person.job} · {person.city}</Text><Text style={[styles.text,{marginTop:12}]}>{person.bio}</Text><View style={ui.pills}>{person.interests.map(i=><Pill key={i} label={i} onPress={()=>{}}/>)}</View><Button label={person.mutual?'Chat with '+person.name:'Follow'} onPress={async()=>{if(person.mutual)return openChat(person);try{const res=await api<{mutual:boolean}>(`/users/${person.id}/follow`,{method:'POST'});setPerson({...person,mutual:res.mutual});Alert.alert(res.mutual?'Friends now':'Following',res.mutual?'You can chat now.':'Chat opens after mutual follow.')}catch(e){notify(e)}}}/></View><Text style={[styles.heading,{marginTop:24}]}>Real profile</Text><Text style={styles.muted}>Real photo galleries are enabled when media upload is configured. The graph uses agent avatars.</Text>{encounter?.candidate?.id===person.id&&<TouchableOpacity onPress={()=>openEncounter(encounter)} style={[styles.card,{marginTop:18}]}><Text style={ui.rowTitle}>Why your agent recommends {person.name} ›</Text><Text style={styles.muted}>{encounter.reason}</Text></TouchableOpacity>}</ScrollView></>;
    if(page==='Encounter'&&detail)return <>{header('Agent encounter','Explore')}<ScrollView contentContainerStyle={styles.body}><View style={[ui.graph,{height:170}]}><View style={{flexDirection:'row',alignItems:'center',gap:60}}><Avatar size={78} outfit={me?.outfit}/><Text style={{fontSize:23,color:c.teal}}>···→</Text><Avatar size={78} outfit={encounter?.candidate?.outfit}/></View></View><Section title="Why my agent noticed them"><View style={styles.card}><Text style={styles.text}>{detail.reason}</Text><Text style={[styles.muted,{marginTop:10}]}>Path: {detail.path?.join(' → ')}</Text></View></Section><Section title="Public post evidence">{detail.evidence?.length?detail.evidence.map(p=><View key={p.post_id} style={[styles.card,{marginBottom:8}]}><Text style={styles.text}>{p.excerpt}</Text></View>):<Text style={styles.muted}>They don't post publicly; your agents crossed paths through the circle.</Text>}</Section><Section title="Agent-to-agent transcript">{detail.turns.length?detail.turns.map((turn,i)=><View key={i} style={[styles.card,{marginBottom:8,backgroundColor:turn.speaker_id===me?.id?c.mint:c.white}]}><Text style={styles.muted}>{turn.speaker_id===me?.id?'Your agent':`${encounter?.candidate?.name}'s agent`}</Text><Text style={styles.text}>{turn.body}</Text></View>):<Text style={styles.muted}>No agent conversation yet. Both people must allow it.</Text>}</Section><Button label="Let our agents talk" onPress={async()=>{try{setDetail(await api<Detail>(`/encounters/${detail.id}/agent-chat`,{method:'POST'}))}catch(e){notify(e)}}}/><View style={{height:10}}/><Button label="View real profile" secondary onPress={()=>encounter?.candidate&&openPerson(encounter.candidate.id)}/></ScrollView></>;
    if(page==='Chats')return <ScrollView contentContainerStyle={styles.body}><Text style={styles.title}>Chats</Text><Field placeholder="Search by Aeolia ID" value={query} onChangeText={setQuery} style={{marginTop:16}}/><Button label="Add by ID" secondary onPress={async()=>{try{const p=await api<Person>(`/users/by-id/${encodeURIComponent(query)}`);setPerson(p);setPage('Person')}catch(e){notify(e)}}}/><View style={{height:16}}/>{userRow(me||{id:1,name:'My agent',handle:'',city:'',job:'',bio:'',interests:[],outfit:'teal'},()=>setPage('Agent'),'Pinned · Getting to know you')}<TouchableOpacity onPress={()=>setFriendsOpen(!friendsOpen)} style={ui.group}><Text style={ui.rowTitle}>Friends</Text><Text style={ui.rowTitle}>{friendsOpen?'⌄':'›'}</Text></TouchableOpacity>{friendsOpen&&[2,3,4].map((id)=><ChatPreview key={id} id={id} openChat={openChat}/>)}<TouchableOpacity onPress={()=>setGroupsOpen(!groupsOpen)} style={ui.group}><Text style={ui.rowTitle}>Groups</Text><Text style={ui.rowTitle}>{groupsOpen?'⌄':'›'}</Text></TouchableOpacity>{groupsOpen&&<Text style={[styles.muted,{margin:10}]}>Group messaging is planned for the next milestone.</Text>}</ScrollView>;
    if(page==='Conversation'&&person)return <>{header(person.name,'Chats')}<View style={{flex:1,padding:16}}><View style={[styles.card,{backgroundColor:c.apricot,marginBottom:16}]}><Text style={ui.rowTitle}>Introduced by your agents</Text><Text style={styles.muted}>{encounter?.candidate?.id===person.id?encounter.reason:'You can take it from here.'}</Text></View><ScrollView style={{flex:1}}>{messages.map(m=><View key={m.id} style={[styles.card,{alignSelf:m.sender_id===me?.id?'flex-end':'flex-start',backgroundColor:m.sender_id===me?.id?c.mint:c.white,marginBottom:9,maxWidth:'85%'}]}><Text style={styles.text}>{m.body}</Text></View>)}</ScrollView><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined}><View style={{flexDirection:'row',gap:6,alignItems:'center'}}><Field placeholder={`Message ${person.name}…`} value={draft} onChangeText={setDraft} style={{flex:1,marginBottom:0}}/><TouchableOpacity onPress={async()=>{if(!draft.trim())return;try{await api('/messages',json('POST',{recipient_id:person.id,body:draft}));setDraft('');setMessages(await api<typeof messages>(`/messages/${person.id}`))}catch(e){notify(e)}}}><Text style={{fontSize:27,color:c.teal}}>➤</Text></TouchableOpacity></View></KeyboardAvoidingView><Text style={[styles.muted,{marginTop:8}]}>Image, voice and video calling UI will be added with media services.</Text></View></>;
    if(page==='Events')return <>{header('Events')}<ScrollView contentContainerStyle={styles.body}><Text style={[styles.muted,{marginBottom:20}]}>In-person plans and online game rooms from friends.</Text>{events.length?events.map(e=><View key={e.id} style={[styles.card,{marginBottom:12}]}><Text style={styles.muted}>{e.kind==='game'?'Online game':'In-person meetup'}</Text><Text style={ui.rowTitle}>{e.title}</Text><Text style={styles.muted}>By {e.creator.name}{e.location?' · '+e.location:''}</Text><View style={{height:10}}/><Button label={e.kind==='game'?'Join room':'View plan'} onPress={()=>e.kind==='game'?setPage('Game'):Alert.alert(e.title,'Plan details will appear here.')}/></View>):<Text style={styles.muted}>No plans yet. Invite your friends to start one.</Text>}<Button label="Create an event" secondary onPress={()=>setPage('Create')}/></ScrollView></>;
    if(page==='Game')return <>{header('Draw & Guess','Events')}<View style={[styles.body,{flex:1}]}><Text style={styles.muted}>Friends room · Invite friends to play online</Text><View style={[styles.card,{flex:1,alignItems:'center',justifyContent:'center',marginVertical:24}]}><Text style={{fontSize:60,color:c.teal}}>☕</Text><Text style={styles.muted}>Shared drawing canvas</Text></View><Field placeholder="Guess the word…"/><Button label="Invite friends" onPress={()=>Alert.alert('Coming next','Real-time multiplayer will be added with WebSockets.')}/></View></>;
    if(page==='Settings')return <>{header('Settings','Profile')}<ScrollView contentContainerStyle={styles.body}>{['Profile & avatar','Agent preferences & memory','Agent exploration permissions','Privacy & visibility','Notifications'].map(x=><TouchableOpacity key={x} style={[styles.card,{marginBottom:10}]} onPress={()=>setPage(x.includes('Agent')?'Agent':'Profile')}><Text style={ui.rowTitle}>{x}  ›</Text></TouchableOpacity>)}<Section title="Discovery permissions"><View style={[styles.card,{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}]}><Text style={styles.text}>Allow my agent to be discovered</Text><Switch value={!!me?.agent_discoverable} onValueChange={async(v)=>{try{setMe(await api<Person>('/me',json('PATCH',{agent_discoverable:v})))}catch(e){notify(e)}}}/></View><View style={[styles.card,{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8}]}><Text style={styles.text}>Allow agent-to-agent chat</Text><Switch value={!!me?.agent_chat_allowed} onValueChange={async(v)=>{try{setMe(await api<Person>('/me',json('PATCH',{agent_chat_allowed:v})))}catch(e){notify(e)}}}/></View></Section><Button label="Subscription · Free plan" onPress={()=>setPage('Plus')} secondary/></ScrollView></>;
    if(page==='Plus')return <>{header('Aeolia Plus','Settings')}<ScrollView contentContainerStyle={styles.body}><Text style={styles.title}>Let your agent explore further</Text><Text style={[styles.muted,{marginVertical:18}]}>Your profile, posts, friends and human chats stay free.</Text><View style={styles.card}><Text style={styles.heading}>Free</Text><Text style={styles.text}>Limited agent exploration · All social features</Text></View><View style={[styles.card,{marginTop:12,borderColor:c.teal}]}><Text style={styles.heading}>Plus</Text><Text style={styles.text}>More exploration sessions across multiple circles</Text></View><Text style={[styles.muted,{marginTop:16}]}>Subscription purchase flow is not enabled in this demo. No charges can occur.</Text></ScrollView></>;
    return null;
  };
  return <View style={styles.page}><StatusBar barStyle="dark-content"/>{pageContent()}{TABS.includes(page)&&<View style={ui.nav}>{TABS.map((t,i)=><TouchableOpacity key={t} onPress={()=>goTab(t)} style={ui.tab}><Text style={{color:page===t?c.teal:c.muted,fontSize:25}}>{['⌂','⌕','⊕','☏','♙'][i]}</Text><Text style={{color:page===t?c.teal:c.muted,fontSize:11,fontWeight:page===t?'700':'400'}}>{t}</Text></TouchableOpacity>)}</View>}</View>;
}

function CirclePosts({id,openPerson}:{id:number;openPerson:(id:number)=>void}){const [posts,setPosts]=useState<Post[]>([]);useEffect(()=>{api<Post[]>(`/circles/${id}/posts`).then(setPosts).catch(()=>{})},[id]);return <>{posts.map(p=><View key={p.id} style={[styles.card,{marginBottom:10}]}><TouchableOpacity onPress={()=>openPerson(p.author.id)} style={{flexDirection:'row',alignItems:'center',gap:10}}><Avatar size={36} outfit={p.author.outfit}/><Text style={ui.rowTitle}>{p.author.name}</Text></TouchableOpacity><Text style={[styles.text,{marginTop:10}]}>{p.body}</Text></View>)}</>}
function ChatPreview({id,openChat}:{id:number;openChat:(p:Person)=>void}){const [p,setP]=useState<Person|null>(null);useEffect(()=>{api<Person>(`/users/${id}`).then(setP).catch(()=>{})},[id]);return p?<TouchableOpacity onPress={()=>openChat(p)} style={ui.row}><Avatar outfit={p.outfit}/><View style={{marginLeft:12}}><Text style={ui.rowTitle}>{p.name}</Text><Text style={styles.muted}>{p.mutual?'Tap to chat':'Follow each other to chat'}</Text></View></TouchableOpacity>:null}
const ui=StyleSheet.create({brand:{color:c.teal,fontSize:25,fontWeight:'800',marginTop:10},header:{paddingTop:50,paddingBottom:12,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:c.bg,borderBottomWidth:1,borderBottomColor:c.line},back:{fontSize:36,color:c.ink,lineHeight:35},headerTitle:{fontSize:18,fontWeight:'700',color:c.ink},homeShortcut:{width:'49%',minHeight:133,alignItems:'center',justifyContent:'center'},shortcutIcon:{fontSize:29,color:c.teal,marginBottom:10},row:{flexDirection:'row',alignItems:'center',paddingVertical:14,borderBottomWidth:1,borderColor:c.line},rowTitle:{color:c.ink,fontSize:16,fontWeight:'700'},pills:{flexDirection:'row',flexWrap:'wrap',marginTop:10,marginBottom:12},graph:{backgroundColor:c.white,borderRadius:18,borderWidth:1,borderColor:c.line,height:295,justifyContent:'center',alignItems:'center',overflow:'hidden'},graphLine:{position:'absolute',width:'90%',height:1,backgroundColor:c.mint,transform:[{rotate:'-27deg'}]},graphLine2:{position:'absolute',width:'90%',height:1,backgroundColor:c.mint,transform:[{rotate:'25deg'}]},group:{backgroundColor:c.mint,padding:13,borderRadius:12,flexDirection:'row',justifyContent:'space-between',marginTop:20},nav:{height:70,paddingBottom:12,borderTopWidth:1,borderColor:c.line,backgroundColor:c.white,flexDirection:'row',justifyContent:'space-around'},tab:{alignItems:'center',justifyContent:'center',flex:1}});
